server:
  port: 8079
spring:
  application:
    name: leyou-service
  datasource:
    url: jdbc:mysql:///mall
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.item.pojo